### ISSUE TITLE
incorrect warning in validator : WARNING: Resource type 'sc:Sequence' should have '@id' set 

### ISSUE THREAD

**Issue by saracarl** [IIIF/presentation-validator#26]
A manifest that does have an @id set is getting the following warning:

WARNING: Resource type 'sc:Sequence' should have '@id' set 

sequence in the manifest:
 "sequences": [
    {
      "@id": "http://70.112.74.2:3000/iiif/1/sequence/default",
      "@type": "sc:Sequence",

or full manifest attached.

[Sequence-manifest.json.txt](https://github.com/IIIF/presentation-api/files/461710/Sequence-manifest.json.txt)

This is using http://iiif.io/api/presentation/validator/ as of today.

**Comment by azaroth42** [comment]
Agreed, that's very strange.

By the way, in the manifest, you have otherContent on the Manifest referring to a Layer.  OtherContent should refer to Annotation Lists, rather than Layers.  e.g. per the second example of http://iiif.io/api/presentation/2.1/#comment-annotations

There isn't a way to refer directly from a Manifest to a Layer -- if you have a use case for this, could you open an issue with it on the iiif.io repository?  Many thanks!

**Comment by azaroth42** [comment]
Fixed! :)
